#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMONEW.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataWeb")]
	public partial class DEMODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertMenus(Menus instance);
    partial void UpdateMenus(Menus instance);
    partial void DeleteMenus(Menus instance);
    partial void InsertPageItem(PageItem instance);
    partial void UpdatePageItem(PageItem instance);
    partial void DeletePageItem(PageItem instance);
    #endregion
		
		public DEMODataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataWebConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DEMODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DEMODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DEMODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DEMODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Menus> Menus
		{
			get
			{
				return this.GetTable<Menus>();
			}
		}
		
		public System.Data.Linq.Table<PageItem> PageItems
		{
			get
			{
				return this.GetTable<PageItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accounts")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private string _Fullname;
		
		private System.Nullable<byte> _Permission;
		
		private string _Email;
		
		private System.Nullable<bool> _Lock;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<Menus> _Menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFullnameChanging(string value);
    partial void OnFullnameChanged();
    partial void OnPermissionChanging(System.Nullable<byte> value);
    partial void OnPermissionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLockChanging(System.Nullable<bool> value);
    partial void OnLockChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public Account()
		{
			this._Menus = new EntitySet<Menus>(new Action<Menus>(this.attach_Menus), new Action<Menus>(this.detach_Menus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(100)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this.OnFullnameChanging(value);
					this.SendPropertyChanging();
					this._Fullname = value;
					this.SendPropertyChanged("Fullname");
					this.OnFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="TinyInt")]
		public System.Nullable<byte> Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lock", DbType="Bit")]
		public System.Nullable<bool> Lock
		{
			get
			{
				return this._Lock;
			}
			set
			{
				if ((this._Lock != value))
				{
					this.OnLockChanging(value);
					this.SendPropertyChanging();
					this._Lock = value;
					this.SendPropertyChanged("Lock");
					this.OnLockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Menus", Storage="_Menus", ThisKey="Username", OtherKey="UserAdd")]
		public EntitySet<Menus> Menus
		{
			get
			{
				return this._Menus;
			}
			set
			{
				this._Menus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Menus(Menus entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Menus(Menus entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menus")]
	public partial class Menus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_MN;
		
		private System.Nullable<long> _Parent;
		
		private System.Nullable<byte> _Pos;
		
		private string _Lable;
		
		private string _UrlLink;
		
		private System.Nullable<long> _OrderKey;
		
		private string _UserAdd;
		
		private string _UserTest;
		
		private System.Nullable<bool> _Hide;
		
		private EntitySet<PageItem> _PageItems;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MNChanging(long value);
    partial void OnID_MNChanged();
    partial void OnParentChanging(System.Nullable<long> value);
    partial void OnParentChanged();
    partial void OnPosChanging(System.Nullable<byte> value);
    partial void OnPosChanged();
    partial void OnLableChanging(string value);
    partial void OnLableChanged();
    partial void OnUrlLinkChanging(string value);
    partial void OnUrlLinkChanged();
    partial void OnOrderKeyChanging(System.Nullable<long> value);
    partial void OnOrderKeyChanged();
    partial void OnUserAddChanging(string value);
    partial void OnUserAddChanged();
    partial void OnUserTestChanging(string value);
    partial void OnUserTestChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    #endregion
		
		public Menus()
		{
			this._PageItems = new EntitySet<PageItem>(new Action<PageItem>(this.attach_PageItems), new Action<PageItem>(this.detach_PageItems));
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="BigInt")]
		public System.Nullable<long> Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this.OnParentChanging(value);
					this.SendPropertyChanging();
					this._Parent = value;
					this.SendPropertyChanged("Parent");
					this.OnParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos", DbType="TinyInt")]
		public System.Nullable<byte> Pos
		{
			get
			{
				return this._Pos;
			}
			set
			{
				if ((this._Pos != value))
				{
					this.OnPosChanging(value);
					this.SendPropertyChanging();
					this._Pos = value;
					this.SendPropertyChanged("Pos");
					this.OnPosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lable", DbType="NVarChar(200)")]
		public string Lable
		{
			get
			{
				return this._Lable;
			}
			set
			{
				if ((this._Lable != value))
				{
					this.OnLableChanging(value);
					this.SendPropertyChanging();
					this._Lable = value;
					this.SendPropertyChanged("Lable");
					this.OnLableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlLink", DbType="VarChar(200)")]
		public string UrlLink
		{
			get
			{
				return this._UrlLink;
			}
			set
			{
				if ((this._UrlLink != value))
				{
					this.OnUrlLinkChanging(value);
					this.SendPropertyChanging();
					this._UrlLink = value;
					this.SendPropertyChanged("UrlLink");
					this.OnUrlLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="BigInt")]
		public System.Nullable<long> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdd", DbType="VarChar(50)")]
		public string UserAdd
		{
			get
			{
				return this._UserAdd;
			}
			set
			{
				if ((this._UserAdd != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserAddChanging(value);
					this.SendPropertyChanging();
					this._UserAdd = value;
					this.SendPropertyChanged("UserAdd");
					this.OnUserAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTest", DbType="VarChar(50)")]
		public string UserTest
		{
			get
			{
				return this._UserTest;
			}
			set
			{
				if ((this._UserTest != value))
				{
					this.OnUserTestChanging(value);
					this.SendPropertyChanging();
					this._UserTest = value;
					this.SendPropertyChanged("UserTest");
					this.OnUserTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_PageItem", Storage="_PageItems", ThisKey="ID_MN", OtherKey="ID_MN")]
		public EntitySet<PageItem> PageItems
		{
			get
			{
				return this._PageItems;
			}
			set
			{
				this._PageItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Menus", Storage="_Account", ThisKey="UserAdd", OtherKey="Username", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Menus.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Menus.Add(this);
						this._UserAdd = value.Username;
					}
					else
					{
						this._UserAdd = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PageItems(PageItem entity)
		{
			this.SendPropertyChanging();
			entity.Menus = this;
		}
		
		private void detach_PageItems(PageItem entity)
		{
			this.SendPropertyChanging();
			entity.Menus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PageItems")]
	public partial class PageItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID_P;
		
		private System.Nullable<long> _ID_MN;
		
		private string _Title;
		
		private string _Sumary;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _CreaDate;
		
		private System.Nullable<System.DateTime> _ModiDate;
		
		private System.Nullable<long> _OrderKey;
		
		private string _UserAdd;
		
		private string _UserTest;
		
		private System.Nullable<bool> _Hide;
		
		private string _Image;
		
		private EntityRef<Menus> _Menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PChanging(long value);
    partial void OnID_PChanged();
    partial void OnID_MNChanging(System.Nullable<long> value);
    partial void OnID_MNChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSumaryChanging(string value);
    partial void OnSumaryChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnCreaDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreaDateChanged();
    partial void OnModiDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModiDateChanged();
    partial void OnOrderKeyChanging(System.Nullable<long> value);
    partial void OnOrderKeyChanged();
    partial void OnUserAddChanging(string value);
    partial void OnUserAddChanged();
    partial void OnUserTestChanging(string value);
    partial void OnUserTestChanged();
    partial void OnHideChanging(System.Nullable<bool> value);
    partial void OnHideChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
		
		public PageItem()
		{
			this._Menus = default(EntityRef<Menus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_P", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID_P
		{
			get
			{
				return this._ID_P;
			}
			set
			{
				if ((this._ID_P != value))
				{
					this.OnID_PChanging(value);
					this.SendPropertyChanging();
					this._ID_P = value;
					this.SendPropertyChanged("ID_P");
					this.OnID_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", DbType="BigInt")]
		public System.Nullable<long> ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					if (this._Menus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sumary", DbType="NVarChar(500)")]
		public string Sumary
		{
			get
			{
				return this._Sumary;
			}
			set
			{
				if ((this._Sumary != value))
				{
					this.OnSumaryChanging(value);
					this.SendPropertyChanging();
					this._Sumary = value;
					this.SendPropertyChanged("Sumary");
					this.OnSumaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreaDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CreaDate
		{
			get
			{
				return this._CreaDate;
			}
			set
			{
				if ((this._CreaDate != value))
				{
					this.OnCreaDateChanging(value);
					this.SendPropertyChanging();
					this._CreaDate = value;
					this.SendPropertyChanged("CreaDate");
					this.OnCreaDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModiDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ModiDate
		{
			get
			{
				return this._ModiDate;
			}
			set
			{
				if ((this._ModiDate != value))
				{
					this.OnModiDateChanging(value);
					this.SendPropertyChanging();
					this._ModiDate = value;
					this.SendPropertyChanged("ModiDate");
					this.OnModiDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="BigInt")]
		public System.Nullable<long> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdd", DbType="VarChar(50)")]
		public string UserAdd
		{
			get
			{
				return this._UserAdd;
			}
			set
			{
				if ((this._UserAdd != value))
				{
					this.OnUserAddChanging(value);
					this.SendPropertyChanging();
					this._UserAdd = value;
					this.SendPropertyChanged("UserAdd");
					this.OnUserAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTest", DbType="VarChar(50)")]
		public string UserTest
		{
			get
			{
				return this._UserTest;
			}
			set
			{
				if ((this._UserTest != value))
				{
					this.OnUserTestChanging(value);
					this.SendPropertyChanging();
					this._UserTest = value;
					this.SendPropertyChanged("UserTest");
					this.OnUserTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hide", DbType="Bit")]
		public System.Nullable<bool> Hide
		{
			get
			{
				return this._Hide;
			}
			set
			{
				if ((this._Hide != value))
				{
					this.OnHideChanging(value);
					this.SendPropertyChanging();
					this._Hide = value;
					this.SendPropertyChanged("Hide");
					this.OnHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(100)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_PageItem", Storage="_Menus", ThisKey="ID_MN", OtherKey="ID_MN", IsForeignKey=true)]
		public Menus Menus
		{
			get
			{
				return this._Menus.Entity;
			}
			set
			{
				Menus previousValue = this._Menus.Entity;
				if (((previousValue != value) 
							|| (this._Menus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menus.Entity = null;
						previousValue.PageItems.Remove(this);
					}
					this._Menus.Entity = value;
					if ((value != null))
					{
						value.PageItems.Add(this);
						this._ID_MN = value.ID_MN;
					}
					else
					{
						this._ID_MN = default(Nullable<long>);
					}
					this.SendPropertyChanged("Menus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
